// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.tokend.wallet.xdr

import org.tokend.wallet.xdr.utils.*

/// Fixed length byte array 
class XdrByteArrayFixed16(byteArray: kotlin.ByteArray): XdrFixedByteArray(byteArray) {
    override val size: Int
        get() = 16
}
